### ISSUE TITLE
Crash Course Pentesting - Intro crash course to penetration testing. -- Room has been made private

### ISSUE THREAD

**Issue by MaximeMnt** [brootware/awesome-cyber-security-university#33]
This room is no longer available, or the link has changed. 
Link: https://tryhackme.com/room/ccpentesting

**Comment by brootware** [comment]
Thank you so much for catching this. @MaximeMnt . I have replaced the room with a new room called HipFlask that does the similar walk through of a pen-testing methodology with the latest PR. https://github.com/brootware/awesome-cyber-security-university/pull/34.

You can check out the new link. Will be closing this for now. Please feel free to open new issues if you ran into any such cases.
