### ISSUE TITLE
TryHackMe Rooms are private

### ISSUE THREAD

**Issue by HarshNarayanJha** [brootware/awesome-cyber-security-university#36]
Hey there!
Thanks for this list, I have just started studying! I'm on `Level 2 - Tooling`, and when I open `nmap`, `web scanning`, `sublist3r`, and `metasploit`, they all come out to be private rooms on TryHackMe... is this intended? I can find another `nmap` and `metasploit` rooms, but can't find the other two

Thanks

**Comment by brootware** [comment]
Hi @HarshNarayanJha , thank you for bringing this up. I just checked from my side and it seems to be working. Can you verify you have logged in?

Web scanning - 
![image](https://github.com/brootware/awesome-cyber-security-university/assets/7734956/c02a735a-0356-43c0-9b06-fbec22623342)

Nmap - 
![image](https://github.com/brootware/awesome-cyber-security-university/assets/7734956/17d3b865-bb4f-4f11-ada7-226d13a9b894)

Sublist3r - 
![image](https://github.com/brootware/awesome-cyber-security-university/assets/7734956/2e717625-4dae-4f4f-bcec-314e9a55a371)

Metasploit - 
![image](https://github.com/brootware/awesome-cyber-security-university/assets/7734956/0bf9b9ea-b024-4733-bac4-0d664c511469)

**Comment by HarshNarayanJha** [comment]
![Screenshot from 2023-06-26 17-30-26](https://github.com/brootware/awesome-cyber-security-university/assets/50262541/5f7325cb-8b6b-465a-882a-6e99007b76be)
Not for me I believe!

**Comment by brootware** [comment]
> Sure!
> 
> May I know how could you access the rooms then?

Hi @HarshNarayanJha , I accessed these rooms a little while back before THM made them private. For now, I found a really good Nmap, Curl and Netcat tutorial and added that in. Still searching for web scanning, sublister and metasploit though.

**Comment by colpireduro** [comment]
Hi @brootware I have problem accessing the nmap, web scanning, sublist3r, and metasploit, it's on private. Can you help me with this?

**Comment by brootware** [comment]
Hello @colpireduro and @HarshNarayanJha could you try https://tryhackme.com/room/nmap01. If it works, I'll modify the list to update the latest one.

**Comment by colpireduro** [comment]
Hi sir @brootware , it worked now, thank you so much!

**Comment by HarshNarayanJha** [comment]
Right @brootware , it does work! Thanks!

**Comment by brootware** [comment]
> Hi sir @brootware , it worked now, thank you so much! Hoping for Netcat and curl :)

Hi @colpireduro , The nmap room should also tackle curl and netcat.
